import SiteHeader from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
      >
        <body
          className={
            inter.className +
            `flex flex-col min-h-screen bg-gradient-to-b dark:from-slate-800 dark:to-slate-900 from-slate-300 to-slate-100`
          }
        >
          <SiteHeader />
          <div className="flex-1 p-16">{children}</div>
        </body>
      </ThemeProvider>
    </html>
  );
}
